### PR TITLE
Add Nano Node Docker to node installers

### PR DESCRIPTION
**Pull request by lephleg**
Also remove the "stack" word as redundant.

### CODE REVIEW

**Comment by Joohansson** [comment]
Normally I don't allow same URL in two different places but your repo is clearly more than just source code. I will merge your PR and think of how to handle cases like this.

**Comment by lephleg** [comment]
You already had Easy Nano Node twice and I suggested the change. Feel free to handle them as you'd like.

**Comment by Joohansson** [comment]
I know but that was not exactly same URL. It was a github page. It’s a bit tricky where to put everything under correct section..

**Comment by Joohansson** [comment]
I know but that was not exactly same URL. It was a github page. It’s a bit tricky where to put everything under correct section..

**Pull request merged**
