### PR TITLE
Added Simple NANO Game

### PR DESCRIPTION
**Pull request by ghost**
Line : 878

### CODE REVIEW

**Comment by Joohansson** [comment]
Sorry I missed this one. Do you still want it added @realmrfas ?

**Comment by realmrfas** [comment]
yes but slight changes in domain :   https://nano.besoeasy.com

SSL issues on old one, since its on IPFS

**Comment by realmrfas** [comment]
@Joohansson

**Comment by Joohansson** [comment]
Done

**Pull request closed without merging**
